words = [
    "EOF",
    "bugprone",
    "cmake",
    "conanfile",
    "cppcoreguidelines",
    "cppstd",
    "ctest",
    "cxx",
    "dcmake",
    "direnv",
    "dscp",
    "hicpp",
    "igmp",
    "ihl",
    "ipv",
    "libcxx",
    "libpcap",
    "lifecycle",
    "nixbuild",
    "nixos",
    "nixpkgs",
    "nullopt",
    "pcapplusplus",
    "pkgs",
    "raii",
    "setcap",
    "stringview",
    "tcpdump",
    "termshark",
    "tshark",
    "udp",
    "werror",
    "wireshark",
]
ignore_paths = ["flake.lock"]
